[package]
name = "bevy-terraria"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
